apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: channels-api           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: channels-api        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: channels-api
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-oasis/channels-api:latest
          name: channels-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8013  # Should match the port number that the Go application listens on
              name: http-port
            - containerPort: 9013  # Should match the port number that the Go application listens on
              name: grpc-port
          env:
            - name: MESSAGE_STORE_URL
              value: "message-store-service.openline.svc.cluster.local:9009"
            - name: OASIS_API_URL
              value: "oasis-api-service.oasis-dev.svc.cluster.local:9006"
            - name: CHANNELS_API_SERVER_ADDRESS
              value: ":8013"
            - name: CHANNELS_GRPC_PORT
              value: "9013"
            - name: SMTP_SERVER_ADDRESS
              value: "my_mail_server"
            - name: SMTP_SERVER_USER
              value: "my_secure_username"
            - name: SMTP_SERVER_PASSWORD
              value: "my_secure_password"
            - name: SMTP_FROM_USER
              value: "demo@example.com"
            - name: MAIL_API_KEY
              value: "nobody-will-guess-this-api-key"
            - name: CHANNELS_API_CORS_URL
              value: "http://localhost:3000"
            - name: WEBCHAT_API_KEY
              value: "nobody-will-guess-this-api-key"
            - name: WEBSOCKET_PING_INTERVAL
              value: "30"              