apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: channels-api-loadbalancer   # Name of the resource
spec:
  type: LoadBalancer
  ports:                         # Take incoming HTTP requests on port 3006 and forward them to the targetPort of 3006
    - name: http
      port: 8013
      targetPort: 8013
  selector:
    app: channels-api         # Map any pod with label `app=oasis-api` to this service