apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: channels-api-service   # Name of the resource
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 10010 and forward them to the targetPort of 1010
    - name: http
      port: 10010
      targetPort: 8013
  selector:
    app: channels-api         # Map any pod with label `app=channels-api` to this service