apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: message-store           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: message-store        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: message-store
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-oasis/message-store:otter
          name: message-store
          imagePullPolicy: Never
          ports:
            - containerPort: 8009  # Should match the port number that the Go application listens on
              name: http-port
            - containerPort: 9009  # Should match the port number that the Go application listens on
              name: grpc-port
          env:
            - name: DB_USER
              value: openline-oasis
            - name: DB_PASSWORD
              value: my-secret-password
            - name: DB_DATABASE
              value: openline-oasis
            - name: DB_HOST
              value: oasis-postgres-service.oasis-dev.svc.cluster.local
            - name: DB_PORT
              value: 5432
