apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: oasis-api-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 10006 and forward them to the targetPort of 8006
    - name: http
      port: 8006
      targetPort: 8006
  selector:
    app: oasis-api         # Map any pod with label `app=oasis-api` to this service