apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: oasis-gui           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: oasis-gui        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: oasis-gui
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-oasis/oasis-frontend-dev:latest
          name: oasis-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 3006  # Should match the port number that the Go application listens on
              name: http-port
          env:
            - name: NEXT_PUBLIC_WEBRTC_WEBSOCKET_URL
              value: "ws://localhost:8080"
            - name: NEXT_PUBLIC_BE_PATH
              value: "http://oasis-api-service.openline.svc.cluster.local:8006"
            - name: NEXT_PUBLIC_CUSTOMER_OS_API_PATH
              value: "http://localhost:10000"
            - name: NEXT_PUBLIC_WEBSOCKET_PATH
              value: "ws://localhost:8006/ws"
            - name: NEXT_PUBLIC_TURN_SERVER
              value: "turn:127.0.0.1:3478?transport=tcp"
            - name: NEXT_PUBLIC_TURN_USER
              value: "foo"
            - name: NEXT_PUBLIC_TURN_CREDENTIAL
              value: "1234"
            - name: OASIS_API_KEY
              value: "10a6747a-97cd-4a6c-bcf5-e4ee89a12567"
            - name: NEXTAUTH_URL
              value: "http://localhost:3006"
            - name: NEXTAUTH_OAUTH_CLIENT_ID
              value: "8f1f74c4-6fcd-11ed-a1eb-0242ac120002"
            - name: NEXTAUTH_OAUTH_CLIENT_SECRET
              value: "XEBSZzdEke9GZTh1YiAzsirRM6FsB0DwN2R1XaUf_Zg"
            - name: NEXTAUTH_OAUTH_TENANT_ID
              value: "7c7b794e-6fcd-11ed-a1eb-0242ac120002"
            - name: NEXTAUTH_OAUTH_SERVER_URL
              value: "http://auth-fusionauth.openline.svc.cluster.local:9011/"
            - name: NEXTAUTH_SECRET
              value: "4691821d-ba37-4870-9626-f0cd6ad15e99"
