apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: oasis-gui-service   # Name of the resource
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 10006 and forward them to the targetPort of 8006
    - name: http
      port: 3006
      targetPort: 3006
  selector:
    app: oasis-gui         # Map any pod with label `app=oasis-api` to this service
