apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: oasis-api           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: oasis-api        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: oasis-api
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-oasis/oasis-api:latest
          name: oasis-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8006  # Should match the port number that the Go application listens on
              name: http-port
            - containerPort: 9006  # Should match the port number that the Go application listens on
              name: grpc-port
          env:
            - name: POSTGRES_USER
              value: "openline"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "openline"
            - name: POSTGRES_HOST
              value: "customer-db-postgresql.openline.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_MAX_CONN
              value: "25"
            - name: POSTGRES_MAX_IDLE_CONN
              value: "10"
            - name: POSTGRES_CONN_MAX_LIFETIME
              value: "0"
            - name: POSTGRES_LOG_LEVEL
              value: "WARN"

            - name: NEO4J_TARGET
              value: "neo4j://customer-db-neo4j.openline.svc.cluster.local:7687"
            - name: NEO4J_AUTH_USER
              value: "neo4j"
            - name: NEO4J_AUTH_PWD
              value: "StrongLocalPa$$$"
            - name: NEO4J_AUTH_REALM
              value: ""
            - name: NEO4J_MAX_CONN_POOL_SIZE
              value: "100"
            - name: NEO4J_LOG_LEVEL
              value: "INFO"

            - name: MESSAGE_STORE_URL
              value: "message-store-api-service.openline.svc.cluster.local:9009"
            - name: MESSAGE_STORE_API_KEY
              value: "f6e26f68-7e69-42fb-9aee-624becc29897"

            - name: CHANNELS_API_URL
              value: "channels-api-service.openline.svc.cluster.local:9013"
            - name: CORS_URL
              value: "http://localhost:3006"
            - name: OASIS_GRPC_PORT
              value: "9006"
            - name: OASIS_API_SERVER_ADDRESS
              value: ":8006"
            - name: WEBRTC_AUTH_SECRET
              value: "2c42a1b6-d776-4083-b0b6-44fecea2d022"
            - name: WEBRTC_AUTH_TTL
              value: "3600"
            - name: WEBSOCKET_PING_INTERVAL
              value: "30"              
