apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: oasis-api           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: oasis-api        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: oasis-api
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-oasis/oasis-api:otter
          name: oasis-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8006  # Should match the port number that the Go application listens on
              name: http-port
            - containerPort: 9006  # Should match the port number that the Go application listens on
              name: grpc-port
          env:
            - name: MESSAGE_STORE_URL
              value: "message-store-service.oasis-dev.svc.cluster.local:9009"
            - name: CHANNELS_API_URL
              value: "channels-api-service.oasis-dev.svc.cluster.local:9013"
            - name: CORS_URL
              value: "http://localhost:3006"
            - name: OASIS_API_SERVER_ADDRESS
              value: ":8006"
            - name: WEBRTC_AUTH_SECRET
              value: "2c42a1b6-d776-4083-b0b6-44fecea2d022"
            - name: WEBRTC_AUTH_TTL
              value: "3600"             
