// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: grpc/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE MessageType = 0
	MessageType_FILE    MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE",
		1: "FILE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE": 0,
		"FILE":    1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcservices_grpcservices_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_grpcservices_grpcservices_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_grpcservices_grpcservices_proto_rawDescGZIP(), []int{0}
}

type MessageDirection int32

const (
	MessageDirection_INBOUND  MessageDirection = 0
	MessageDirection_OUTBOUND MessageDirection = 1
)

// Enum value maps for MessageDirection.
var (
	MessageDirection_name = map[int32]string{
		0: "INBOUND",
		1: "OUTBOUND",
	}
	MessageDirection_value = map[string]int32{
		"INBOUND":  0,
		"OUTBOUND": 1,
	}
)

func (x MessageDirection) Enum() *MessageDirection {
	p := new(MessageDirection)
	*p = x
	return p
}

func (x MessageDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcservices_grpcservices_proto_enumTypes[1].Descriptor()
}

func (MessageDirection) Type() protoreflect.EnumType {
	return &file_grpcservices_grpcservices_proto_enumTypes[1]
}

func (x MessageDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageDirection.Descriptor instead.
func (MessageDirection) EnumDescriptor() ([]byte, []int) {
	return file_grpcservices_grpcservices_proto_rawDescGZIP(), []int{1}
}

type MessageChannel int32

const (
	MessageChannel_WIDGET   MessageChannel = 0
	MessageChannel_MAIL     MessageChannel = 1
	MessageChannel_WHATSAPP MessageChannel = 2
	MessageChannel_FACEBOOK MessageChannel = 3
	MessageChannel_TWITTER  MessageChannel = 4
)

// Enum value maps for MessageChannel.
var (
	MessageChannel_name = map[int32]string{
		0: "WIDGET",
		1: "MAIL",
		2: "WHATSAPP",
		3: "FACEBOOK",
		4: "TWITTER",
	}
	MessageChannel_value = map[string]int32{
		"WIDGET":   0,
		"MAIL":     1,
		"WHATSAPP": 2,
		"FACEBOOK": 3,
		"TWITTER":  4,
	}
)

func (x MessageChannel) Enum() *MessageChannel {
	p := new(MessageChannel)
	*p = x
	return p
}

func (x MessageChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcservices_grpcservices_proto_enumTypes[2].Descriptor()
}

func (MessageChannel) Type() protoreflect.EnumType {
	return &file_grpcservices_grpcservices_proto_enumTypes[2]
}

func (x MessageChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageChannel.Descriptor instead.
func (MessageChannel) EnumDescriptor() ([]byte, []int) {
	return file_grpcservices_grpcservices_proto_rawDescGZIP(), []int{2}
}

type OmniMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      MessageType      `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.MessageType" json:"type,omitempty"`
	Message   string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Username  string           `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Channel   MessageChannel   `protobuf:"varint,4,opt,name=channel,proto3,enum=grpc.MessageChannel" json:"channel,omitempty"`
	Direction MessageDirection `protobuf:"varint,5,opt,name=direction,proto3,enum=grpc.MessageDirection" json:"direction,omitempty"`
}

func (x *OmniMessage) Reset() {
	*x = OmniMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcservices_grpcservices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OmniMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmniMessage) ProtoMessage() {}

func (x *OmniMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpcservices_grpcservices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmniMessage.ProtoReflect.Descriptor instead.
func (*OmniMessage) Descriptor() ([]byte, []int) {
	return file_grpcservices_grpcservices_proto_rawDescGZIP(), []int{0}
}

func (x *OmniMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE
}

func (x *OmniMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OmniMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OmniMessage) GetChannel() MessageChannel {
	if x != nil {
		return x.Channel
	}
	return MessageChannel_WIDGET
}

func (x *OmniMessage) GetDirection() MessageDirection {
	if x != nil {
		return x.Direction
	}
	return MessageDirection_INBOUND
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcservices_grpcservices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcservices_grpcservices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcservices_grpcservices_proto_rawDescGZIP(), []int{1}
}

var File_grpcservices_grpcservices_proto protoreflect.FileDescriptor

var file_grpcservices_grpcservices_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22,
	0xe8, 0x01, 0x0a, 0x0b, 0x4f, 0x6d, 0x6e, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x3c, 0x0a, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x2a, 0x24, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x01, 0x2a, 0x2d, 0x0a, 0x10, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x4e, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x55,
	0x54, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x2a, 0x4f, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x49,
	0x44, 0x47, 0x45, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x57, 0x48, 0x41, 0x54, 0x53, 0x41, 0x50, 0x50, 0x10, 0x02, 0x12, 0x0c,
	0x0a, 0x08, 0x46, 0x41, 0x43, 0x45, 0x42, 0x4f, 0x4f, 0x4b, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x54, 0x57, 0x49, 0x54, 0x54, 0x45, 0x52, 0x10, 0x04, 0x32, 0x8b, 0x01, 0x0a, 0x0c, 0x4f, 0x6d,
	0x6e, 0x69, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x3f, 0x0a, 0x0b, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x6d, 0x6e, 0x69, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x08, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x6d, 0x6e, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x4f, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x6d, 0x6e, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x6f, 0x70, 0x65, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcservices_grpcservices_proto_rawDescOnce sync.Once
	file_grpcservices_grpcservices_proto_rawDescData = file_grpcservices_grpcservices_proto_rawDesc
)

func file_grpcservices_grpcservices_proto_rawDescGZIP() []byte {
	file_grpcservices_grpcservices_proto_rawDescOnce.Do(func() {
		file_grpcservices_grpcservices_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcservices_grpcservices_proto_rawDescData)
	})
	return file_grpcservices_grpcservices_proto_rawDescData
}

var file_grpcservices_grpcservices_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grpcservices_grpcservices_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcservices_grpcservices_proto_goTypes = []interface{}{
	(MessageType)(0),      // 0: grpc.MessageType
	(MessageDirection)(0), // 1: grpc.MessageDirection
	(MessageChannel)(0),   // 2: grpc.MessageChannel
	(*OmniMessage)(nil),   // 3: grpc.OmniMessage
	(*Empty)(nil),         // 4: grpc.Empty
}
var file_grpcservices_grpcservices_proto_depIdxs = []int32{
	0, // 0: grpc.OmniMessage.type:type_name -> grpc.MessageType
	2, // 1: grpc.OmniMessage.channel:type_name -> grpc.MessageChannel
	1, // 2: grpc.OmniMessage.direction:type_name -> grpc.MessageDirection
	3, // 3: grpc.OmniChannels.SendMessage:input_type -> grpc.OmniMessage
	3, // 4: grpc.OmniChannels.SendMail:input_type -> grpc.OmniMessage
	3, // 5: grpc.MessageStore.SaveMessage:input_type -> grpc.OmniMessage
	4, // 6: grpc.OmniChannels.SendMessage:output_type -> grpc.Empty
	4, // 7: grpc.OmniChannels.SendMail:output_type -> grpc.Empty
	4, // 8: grpc.MessageStore.SaveMessage:output_type -> grpc.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpcservices_grpcservices_proto_init() }
func file_grpcservices_grpcservices_proto_init() {
	if File_grpcservices_grpcservices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcservices_grpcservices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OmniMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcservices_grpcservices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcservices_grpcservices_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpcservices_grpcservices_proto_goTypes,
		DependencyIndexes: file_grpcservices_grpcservices_proto_depIdxs,
		EnumInfos:         file_grpcservices_grpcservices_proto_enumTypes,
		MessageInfos:      file_grpcservices_grpcservices_proto_msgTypes,
	}.Build()
	File_grpcservices_grpcservices_proto = out.File
	file_grpcservices_grpcservices_proto_rawDesc = nil
	file_grpcservices_grpcservices_proto_goTypes = nil
	file_grpcservices_grpcservices_proto_depIdxs = nil
}
