apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasis-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oasis-postgres
  template:
    metadata:
      labels:
        app: oasis-postgres
    spec:
      containers:
        - name: oasis-postgres
          image: postgres:13.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: oasis-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: oasis-postgredb
      volumes:
        - name: oasis-postgredb
          persistentVolumeClaim:
            claimName: oasis-postgres-pv-claim
